// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Privelege struct {
	ID          int64          `json:"id"`
	Module      sql.NullString `json:"module"`
	Submodule   sql.NullString `json:"submodule"`
	Ordering    sql.NullString `json:"ordering"`
	Action      sql.NullString `json:"action"`
	Method      sql.NullString `json:"method"`
	Uri         sql.NullString `json:"uri"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullTime   `json:"created_time"`
	UpdatedTime sql.NullTime   `json:"updated_time"`
	Status      int8           `json:"status"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

type RolePrivilege struct {
	ID          int64          `json:"id"`
	Role        int16          `json:"role"`
	Action      sql.NullString `json:"action"`
	Method      sql.NullString `json:"method"`
	Uri         sql.NullString `json:"uri"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

type RoleUser struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	RolesID     int64          `json:"roles_id"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

type User struct {
	ID              int64          `json:"id"`
	StatusOtp       sql.NullInt16  `json:"status_otp"`
	Nik             sql.NullString `json:"nik"`
	Photo           sql.NullString `json:"photo"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Username        string         `json:"username"`
	Email           string         `json:"email"`
	Gender          sql.NullString `json:"gender"`
	Address         sql.NullString `json:"address"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	Password        string         `json:"password"`
	EmailVerifiedAt sql.NullTime   `json:"email_verified_at"`
	RememberToken   sql.NullString `json:"remember_token"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedTime     sql.NullTime   `json:"created_time"`
	UpdatedTime     sql.NullTime   `json:"updated_time"`
	Status          int8           `json:"status"`
}

type UserOtp struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Otp         string         `json:"otp"`
	ExpiredAt   sql.NullTime   `json:"expired_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullTime   `json:"created_time"`
	UpdatedTime sql.NullTime   `json:"updated_time"`
	Status      int8           `json:"status"`
}
