// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePrivelege(ctx context.Context, arg CreatePrivelegeParams) (sql.Result, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error)
	CreateRolePrivelege(ctx context.Context, arg CreateRolePrivelegeParams) (sql.Result, error)
	CreateRoleUser(ctx context.Context, arg CreateRoleUserParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateUserOtp(ctx context.Context, arg CreateUserOtpParams) (sql.Result, error)
	DeleteUser(ctx context.Context, id int64) error
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRolePrivilegesByRole(ctx context.Context, role int16) ([]RolePrivilege, error)
	GetRoleUserByUserID(ctx context.Context, userID int64) (RoleUser, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserOtpByUserID(ctx context.Context, userID int64) (UserOtp, error)
	GetUserPrivileges(ctx context.Context, userID int64) ([]GetUserPrivilegesRow, error)
	GetUserRoles(ctx context.Context, userID int64) ([]GetUserRolesRow, error)
	ListPriveleges(ctx context.Context, status int8) ([]Privelege, error)
	ListRoles(ctx context.Context, status int8) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
