// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createPrivelege = `-- name: CreatePrivelege :execresult
INSERT INTO priveleges (module, submodule, ordering, action, method, uri, created_by, updated_by, created_time, updated_time, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePrivelegeParams struct {
	Module      sql.NullString `json:"module"`
	Submodule   sql.NullString `json:"submodule"`
	Ordering    sql.NullString `json:"ordering"`
	Action      sql.NullString `json:"action"`
	Method      sql.NullString `json:"method"`
	Uri         sql.NullString `json:"uri"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullTime   `json:"created_time"`
	UpdatedTime sql.NullTime   `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) CreatePrivelege(ctx context.Context, arg CreatePrivelegeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrivelege,
		arg.Module,
		arg.Submodule,
		arg.Ordering,
		arg.Action,
		arg.Method,
		arg.Uri,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const createRole = `-- name: CreateRole :execresult
INSERT INTO roles (name, code, created_by, updated_by, created_time, updated_time, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleParams struct {
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRole,
		arg.Name,
		arg.Code,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const createRolePrivelege = `-- name: CreateRolePrivelege :execresult
INSERT INTO role_privileges (role, action, method, uri, created_by, updated_by, created_time, updated_time, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRolePrivelegeParams struct {
	Role        int16          `json:"role"`
	Action      sql.NullString `json:"action"`
	Method      sql.NullString `json:"method"`
	Uri         sql.NullString `json:"uri"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) CreateRolePrivelege(ctx context.Context, arg CreateRolePrivelegeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRolePrivelege,
		arg.Role,
		arg.Action,
		arg.Method,
		arg.Uri,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const createRoleUser = `-- name: CreateRoleUser :execresult
INSERT INTO role_users (user_id, roles_id, created_by, updated_by, created_time, updated_time, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleUserParams struct {
	UserID      int64          `json:"user_id"`
	RolesID     int64          `json:"roles_id"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) CreateRoleUser(ctx context.Context, arg CreateRoleUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoleUser,
		arg.UserID,
		arg.RolesID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    status_otp, nik, photo, first_name, last_name, username, email,
    gender, address, phone_number, password, email_verified_at,
    remember_token, created_by, updated_by, created_time, updated_time, status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	StatusOtp       sql.NullInt16  `json:"status_otp"`
	Nik             sql.NullString `json:"nik"`
	Photo           sql.NullString `json:"photo"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Username        string         `json:"username"`
	Email           string         `json:"email"`
	Gender          sql.NullString `json:"gender"`
	Address         sql.NullString `json:"address"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	Password        string         `json:"password"`
	EmailVerifiedAt sql.NullTime   `json:"email_verified_at"`
	RememberToken   sql.NullString `json:"remember_token"`
	CreatedBy       sql.NullString `json:"created_by"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	CreatedTime     sql.NullTime   `json:"created_time"`
	UpdatedTime     sql.NullTime   `json:"updated_time"`
	Status          int8           `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.StatusOtp,
		arg.Nik,
		arg.Photo,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
		arg.Gender,
		arg.Address,
		arg.PhoneNumber,
		arg.Password,
		arg.EmailVerifiedAt,
		arg.RememberToken,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const createUserOtp = `-- name: CreateUserOtp :execresult
INSERT INTO user_otps (user_id, otp, expired_at, created_by, updated_by, created_time, updated_time, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserOtpParams struct {
	UserID      int64          `json:"user_id"`
	Otp         string         `json:"otp"`
	ExpiredAt   sql.NullTime   `json:"expired_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullTime   `json:"created_time"`
	UpdatedTime sql.NullTime   `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) CreateUserOtp(ctx context.Context, arg CreateUserOtpParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserOtp,
		arg.UserID,
		arg.Otp,
		arg.ExpiredAt,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.Status,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, code, created_by, updated_by, created_time, updated_time, status FROM roles WHERE id = ?
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.Status,
	)
	return i, err
}

const getRolePrivilegesByRole = `-- name: GetRolePrivilegesByRole :many
SELECT id, role, action, method, uri, created_by, updated_by, created_time, updated_time, status FROM role_privileges WHERE role = ? AND status = 1
`

func (q *Queries) GetRolePrivilegesByRole(ctx context.Context, role int16) ([]RolePrivilege, error) {
	rows, err := q.db.QueryContext(ctx, getRolePrivilegesByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePrivilege{}
	for rows.Next() {
		var i RolePrivilege
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Action,
			&i.Method,
			&i.Uri,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleUserByUserID = `-- name: GetRoleUserByUserID :one
SELECT id, user_id, roles_id, created_by, updated_by, created_time, updated_time, status FROM role_users WHERE user_id = ?
`

func (q *Queries) GetRoleUserByUserID(ctx context.Context, userID int64) (RoleUser, error) {
	row := q.db.QueryRowContext(ctx, getRoleUserByUserID, userID)
	var i RoleUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RolesID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, status_otp, nik, photo, first_name, last_name, username, email, gender, address, phone_number, password, email_verified_at, remember_token, created_by, updated_by, created_time, updated_time, status FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StatusOtp,
		&i.Nik,
		&i.Photo,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Gender,
		&i.Address,
		&i.PhoneNumber,
		&i.Password,
		&i.EmailVerifiedAt,
		&i.RememberToken,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.Status,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, status_otp, nik, photo, first_name, last_name, username, email, gender, address, phone_number, password, email_verified_at, remember_token, created_by, updated_by, created_time, updated_time, status FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StatusOtp,
		&i.Nik,
		&i.Photo,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Gender,
		&i.Address,
		&i.PhoneNumber,
		&i.Password,
		&i.EmailVerifiedAt,
		&i.RememberToken,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.Status,
	)
	return i, err
}

const getUserOtpByUserID = `-- name: GetUserOtpByUserID :one
SELECT id, user_id, otp, expired_at, created_by, updated_by, created_time, updated_time, status FROM user_otps WHERE user_id = ? ORDER BY created_time DESC LIMIT 1
`

func (q *Queries) GetUserOtpByUserID(ctx context.Context, userID int64) (UserOtp, error) {
	row := q.db.QueryRowContext(ctx, getUserOtpByUserID, userID)
	var i UserOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Otp,
		&i.ExpiredAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.Status,
	)
	return i, err
}

const getUserPrivileges = `-- name: GetUserPrivileges :many
SELECT 
    rp.id AS id,
    rp.role AS role,
    p.module AS module,
    p.submodule AS submodule,
    p.ordering AS ordering,
    rp.action AS action,
    rp.uri AS uri,
    rp.method AS method,
    rp.created_by AS created_by,
    rp.updated_by AS updated_by,
    rp.created_time AS created_time,
    rp.updated_time AS updated_time,
    rp.status AS status
FROM role_privileges rp
JOIN priveleges p ON 
    rp.action = p.action AND 
    rp.uri = p.uri AND 
    rp.method = p.method
WHERE rp.role IN (
    SELECT roles_id FROM role_users WHERE user_id = ?
) AND rp.status = 1
`

type GetUserPrivilegesRow struct {
	ID          int64          `json:"id"`
	Role        int16          `json:"role"`
	Module      sql.NullString `json:"module"`
	Submodule   sql.NullString `json:"submodule"`
	Ordering    sql.NullString `json:"ordering"`
	Action      sql.NullString `json:"action"`
	Uri         sql.NullString `json:"uri"`
	Method      sql.NullString `json:"method"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	CreatedTime sql.NullString `json:"created_time"`
	UpdatedTime sql.NullString `json:"updated_time"`
	Status      int8           `json:"status"`
}

func (q *Queries) GetUserPrivileges(ctx context.Context, userID int64) ([]GetUserPrivilegesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPrivileges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPrivilegesRow{}
	for rows.Next() {
		var i GetUserPrivilegesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Module,
			&i.Submodule,
			&i.Ordering,
			&i.Action,
			&i.Uri,
			&i.Method,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT 
    ru.id AS id,
    ru.user_id AS user_id,
    r.id AS role_id,
    r.name AS role_name,
    r.code AS role_code,
    r.created_by AS role_created_by,
    r.updated_by AS role_updated_by,
    r.created_time AS role_created_time,
    r.updated_time AS role_updated_time,
    r.status AS role_status,
    ru.created_by AS ru_created_by,
    ru.updated_by AS ru_updated_by,
    ru.created_time AS ru_created_time,
    ru.updated_time AS ru_updated_time,
    ru.status AS ru_status
FROM role_users ru
JOIN roles r ON ru.roles_id = r.id
WHERE ru.user_id = ?
`

type GetUserRolesRow struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	RoleID          int64          `json:"role_id"`
	RoleName        string         `json:"role_name"`
	RoleCode        string         `json:"role_code"`
	RoleCreatedBy   sql.NullString `json:"role_created_by"`
	RoleUpdatedBy   sql.NullString `json:"role_updated_by"`
	RoleCreatedTime sql.NullString `json:"role_created_time"`
	RoleUpdatedTime sql.NullString `json:"role_updated_time"`
	RoleStatus      int8           `json:"role_status"`
	RuCreatedBy     sql.NullString `json:"ru_created_by"`
	RuUpdatedBy     sql.NullString `json:"ru_updated_by"`
	RuCreatedTime   sql.NullString `json:"ru_created_time"`
	RuUpdatedTime   sql.NullString `json:"ru_updated_time"`
	RuStatus        int8           `json:"ru_status"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]GetUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.RoleName,
			&i.RoleCode,
			&i.RoleCreatedBy,
			&i.RoleUpdatedBy,
			&i.RoleCreatedTime,
			&i.RoleUpdatedTime,
			&i.RoleStatus,
			&i.RuCreatedBy,
			&i.RuUpdatedBy,
			&i.RuCreatedTime,
			&i.RuUpdatedTime,
			&i.RuStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriveleges = `-- name: ListPriveleges :many
SELECT id, module, submodule, ordering, action, method, uri, created_by, updated_by, created_time, updated_time, status FROM priveleges WHERE status = COALESCE(?, status)
`

func (q *Queries) ListPriveleges(ctx context.Context, status int8) ([]Privelege, error) {
	rows, err := q.db.QueryContext(ctx, listPriveleges, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Privelege{}
	for rows.Next() {
		var i Privelege
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Submodule,
			&i.Ordering,
			&i.Action,
			&i.Method,
			&i.Uri,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, code, created_by, updated_by, created_time, updated_time, status FROM roles WHERE status = COALESCE(?, status)
`

func (q *Queries) ListRoles(ctx context.Context, status int8) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, status_otp, nik, photo, first_name, last_name, username, email, gender, address, phone_number, password, email_verified_at, remember_token, created_by, updated_by, created_time, updated_time, status FROM users
WHERE status = COALESCE(?, status)
ORDER BY created_time DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Status int8  `json:"status"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.StatusOtp,
			&i.Nik,
			&i.Photo,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Email,
			&i.Gender,
			&i.Address,
			&i.PhoneNumber,
			&i.Password,
			&i.EmailVerifiedAt,
			&i.RememberToken,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = ?, updated_by = ?, updated_time = ? WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status      int8           `json:"status"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	UpdatedTime sql.NullTime   `json:"updated_time"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.UpdatedTime,
		arg.ID,
	)
	return err
}
